### ISSUE TITLE
Allow specifying a GH repository for Homebrew Tap 

### ISSUE THREAD

**Issue by panmau** [xoofx/dotnet-releaser#15]
I haven't given this a try yet but it seems to be quite good already and just like what I need as all that build  / packaging stuff just gives me a headache 😄 

For the Homebrew option I'd prefer to have a single Tap Repository (like homebrew-myusername) that will contain the different Formulaes for the different tools I maintain instead of a new Tap for each Formulae. 
Does it make sense to you if dotnet-releaser supported this possibility? If you think that it overcomplicates things too much, I don't think it should be added. I would be able to live without it 😃  

I'm not sure what the best way to configure it would be. My first thought was that you can add a GitHub repository link and if it is set it will use that for the Formulae creation/update. Otherwise it will use the default path for it.

**Comment by xoofx** [comment]
Tried to prototype it in commit 21c3ed7. You should be able to specify your own homebrew repository in the config file:

```toml
[brew]
home = "homebrew-all-my-apps"
```

Does it cover your case? The GitHub user would be the same than the one configured from the `[github]` section. Not sure it is relevant to have a different user for the published homebrew.

**Comment by panmau** [comment]
Thanks! :sparkles: Yes, that would fully cover my case. 
I agree that it makes sense that the Tap and App are published under the same user. So no need to change anything about that.
