### ISSUE TITLE
Add support for obfuscation

### ISSUE THREAD

**Issue by jaszczykj** [xoofx/dotnet-releaser#26]
dotnet pack should use obfuscated packages

**Comment by xoofx** [comment]
I will decline this for now. I believe you can integrate obfuscation directly in your csproj and dotnet-releaser will pick-up whatever you have setup from your csproj.
Also, the main goal of dotnet-releaser is to ease the publishing process for public OSS projects. You can definitely obfuscate your private projects but you are on your own.
