### ISSUE TITLE
New command requires configuration file

### ISSUE THREAD

**Issue by phil-scott-78** [xoofx/dotnet-releaser#30]
```
dotnet-releaser new --project soddi.csproj
The dotnet-releaser.toml field is required.
```

I suspect just swapping the bool here https://github.com/xoofx/dotnet-releaser/blob/main/src/dotnet-releaser/ReleaserApp.cs#L107 would fix things up.

**Comment by xoofx** [comment]
Thanks! Fixed by commit c7b05fa. Will be available in `0.3.3+`
