### ISSUE TITLE
SHA256 mismatch when installing new version via Homebrew

### ISSUE THREAD

**Issue by panmau** [xoofx/dotnet-releaser#34]
I triggered [a new build](https://github.com/panmau/switchtube-dl/actions/runs/1924869852) with version 0.3.14 as I wasn't able to install a new version of my package with homebrew.

I am now running into the following error when running `brew upgrade`:
```
Error: SHA256 mismatch
Expected: fa9c3240a704b320ed11170de1c1dcc43478e65b700d530d5c2c947d5f42f067
  Actual: e149124b7bdcbb54c7c4105734829fecbc32f31d8586097e7457878ac1403a76
```

The `Actual` value of the SHA256 doesn't match though with any of the generated SHA values of dotnet-releaser, neither before nor after this specific build, as can be seen in [this commit](https://github.com/panmau/homebrew-panmau/commit/a96dc7ca90672641384a8b8663c9faa4a7269634)

Do you have any idea what could be happening here?
Thanks in advance again!

**Comment by xoofx** [comment]
Weird, I tried on grpc-curl today and it worked. I will investigate tomorrow

**Comment by xoofx** [comment]
I verified on my own project and the hash is correct but From your logs, it seems that these packages were already published with that tag, so the 2nd time they were not uploaded, but the formula was updated.
Republishing a same version is not supported. You would have to remove the uploaded files in your release manually and retrigger a publish

**Comment by panmau** [comment]
> I verified on my own project and the hash is correct but From your logs, it seems that these packages were already published with that tag, so the 2nd time they were not uploaded, but the formula was updated. Republishing a same version is not supported. You would have to remove the uploaded files in your release manually and retrigger a publish

What is weird though, is that the hashes from the initial publish don't match either to the ones that homebrew expects. 
I will try out what happens when I remove the uploaded files in my release and report back.

**Comment by panmau** [comment]
Works perfectly after removing the files and re-running the job.
