### ISSUE TITLE
Central package management 

### ISSUE THREAD

**Issue by JamieMagee** [xoofx/dotnet-releaser#35]
Attempting to use dotnet-releaser with NuGet Central Package Management[^1] I get the error:

```
error NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion
items: Packaging.Targets.
```

[^1]: https://devblogs.microsoft.com/nuget/introducing-central-package-management/
[^2]: https://github.com/xoofx/dotnet-releaser/blob/913ce49c79eb3b3bbcee9a95b3d325e6d34192b8/src/dotnet-releaser/dotnet-releaser.targets#L3

**Comment by xoofx** [comment]
Hopefully fixed by 0aea1e5. Not sure if it is the best way to workaround it. A bit annoying to have to create entirely different ItemGroup path for them.
