### ISSUE TITLE
NU1504 error on test project with coverlet.collector reference

### ISSUE THREAD

**Issue by kashelkin** [xoofx/dotnet-releaser#42]
I have test project with coverlet.collector reference. Recently dotnet-releaser started to throw this error on [9] step:
```
error NU1504: Duplicate 'PackageReference' items found. 
Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. 
The duplicate 'PackageReference' items are: coverlet.collector 3.1.0, coverlet.collector 3.1.*.
```
It seems that it happens after new NuGet 6.3 [release](https://devblogs.microsoft.com/nuget/announcing-nuget-6-3-transitive-dependencies-floating-versions-and-re-enabling-signed-package-verification/). They introduced new warnings for duplicate package references, versions and downloads.

I added this to my project file as workaround:
```
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
  <NoWarn>1504</NoWarn>
</PropertyGroup>
```

**Comment by xoofx** [comment]
Indeed, there is not many options, either:

- remove the `coverlet.collector` package from your test project
- or disable the coverage in dotnet-releaser
