### ISSUE TITLE
Unable to use this with .NET Framework 4.8 projects

### ISSUE THREAD

**Issue by 3UR** [xoofx/dotnet-releaser#50]
When I attempt to use this with any .NET 4.8 project I am faced with the following message : `The project 'projectpath' doesn't not have a <TargetFramework> or <TargetFrameworks> defined` is this a bug?

**Comment by 3UR** [comment]
instead of TargetFramework/TargetFrameworks it seems to use '<TargetFrameworkVersion>v4.8</TargetFrameworkVersion>'

**Comment by xoofx** [comment]
> NET 4.8 project

You mean old csproj project? If yes, these are not supported.
