### ISSUE TITLE
Does this works with .net 7 Asp Net Core?

### ISSUE THREAD

**Issue by franklupo** [xoofx/dotnet-releaser#54]
Does this works with .net 7 Asp Net Core?

**Comment by FrediKats** [comment]
I checked it locally with my Aspire + Blazor + ASP.NET solution. dotnet-release build and run tests without problems. But you must set `<IsPackable>false</IsPackable>` in `Directory.Build.props` to prevent NuGet packing of your projects. I'm also going to test this dotnet-releaser as main CI for ASP project for build + test + generate changelog.

I expected that I can use subset of functionality for projects that is not NuGet packages (like ASP):
![image](https://github.com/xoofx/dotnet-releaser/assets/22368203/a3e9c5a8-2de5-460d-8fae-9d899bd1e39b)
