### ISSUE TITLE
chmod +x on executables

### ISSUE THREAD

**Issue by Deadpikle** [xoofx/dotnet-releaser#63]
Hi,

Just came across this project and looks great! Thank you!

I am testing here building for macOS (from macOS). The single file output is not marked as executable (`chmod +x`), which means the end user will have to do it themselves to run the software. Is there an option to do this through `dotnet-releaser`?

Edit: To be clear, `dotnet publish -r osx-x64`'s output _is_ executable. And the output in the `bin` folder is executable, so this may be an issue with the final zip/tar stage or similar?

Edit 2: Probably related: https://github.com/quamotion/dotnet-packaging/issues/134

**Comment by xoofx** [comment]
That's weird, because dotnet publish does produce executable, but I forgot the details. I believe it is more related to the `tar.gz` that is not picking this correctly or similar.

Don't have time to investigate this, so PR welcome.

**Comment by Deadpikle** [comment]
For anyone who works on this in the future:

Fairly certain this is an upstream issue, see https://github.com/quamotion/dotnet-packaging/issues/134. Have confirmed that the output of the build from this lib is executable, but the packaging process kills the executable bit.

I dug into `dotnet-packaging` for a while, and basically they are making their own tarballs and lots of other fun stuff that makes this harder for me to see how to fix. (Why they are not using a lib to build the tarball is not known at this time.) (See files like https://github.com/quamotion/dotnet-packaging/blob/14f2bd2db4beaec82676f501f62137863358473c/Packaging.Targets/IO/TarFileCreator.cs#L46). There is probably some header for executable bits not being carried over properly. There are also not unit tests for these features in that project to easily start hacking away at a fix.

Options I see:

* Manually find and add the +x on the app host executable if there is a reliable way to do that. Can that be retrieved easily from `RunMSBuild`? (Build without the specific target maybe?)
* Not using `dotnet-packaging`, doing the publish yourself, and then just tar'ing/zip'ing the output using a standardized lib that's easier to work with. [There's built-in TAR support in .NET 7/8](https://andrewlock.net/working-with-tar-files-in-dotnet/).

Something as simple as:

```csharp
string sourceDir = "/Users/.../dotnet-releaser/tests/HelloWorld/bin/Release/net6.0/osx-x64/publish";
string outputFile = "/Users/.../Desktop/test.tar.gz";

using FileStream fs = new(outputFile, FileMode.CreateNew, FileAccess.Write);
using GZipStream gz = new(fs, CompressionMode.Compress, leaveOpen: true);

TarFile.CreateFromDirectory(sourceDir, gz, includeBaseDirectory: false);
```

Works just fine and keeps the executable bit as appropriate after a quick test.

If `dotnet-packaging` is the problem, and the answer is as simply as tarball'ing up the `publish` directory (if this is truly all the lib is doing?), is that a viable solution for `dotnet-releaser`...?
