### ISSUE TITLE
Build Failure on Windows using msbuild with a VS project

### ISSUE THREAD

**Issue by EmeraldMike** [xoofx/dotnet-releaser#8]
```
dotnet-releaser[28]
      Failing to run dotnet msbuild -p:PublishTrimmed=true -p:PublishSingleFile=true -p:SelfContained=true -p:PublishReadyToRun=true -p:CopyOutputSymbolsToPublishDirectory=false -p:SkipCopyingSymbolsToOutputDirectory=true -p:RuntimeIdentifier=rhel-x64 -p:Configuration=Release -p:CustomAfterMicrosoftCommonTargets="C:\Users\Emera\.dotnet\tools\.store\dotnet-releaser\0.1.0\dotnet-releaser\0.1.0\tools\net6.0\any\dotnet-releaser.targets" -nologo -logger:BinaryLogger,"C:\Users\Emera\.dotnet\tools\.store\dotnet-releaser\0.1.0\dotnet-releaser\0.1.0\tools\net6.0\any\dotnet-releaser-binary-logger.dll";"C:\Users\Emera\AppData\Local\Temp\tmp18AA.tmp.binlog" -t:DotNetReleaserPublishAndCreateTar C:\Users\Emera\source\repos\catoscript\cato\cato.csproj. Reason: C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(2929,5): error : MSB4803: The task "ResolveComReference" is not supported on the .NET Core version of MSBuild. Please use the .NET Framework version of MSBuild. See https://aka.ms/msbuild/MSB4803 for further details. [C:\Users\Emera\source\repos\catoscript\cato\cato.csproj]
```
this happens for any type of build

**Comment by xoofx** [comment]
What kind of projects are you trying to build? It is unlikely to work on old .NET Framework projects, `dotnet-releaser` is gonna be mainly usable with .NET6.0+ apps... forgot to mention that on the readme...

**Comment by EmeraldMike** [comment]
NuGet is disabled if that helps

**Comment by EmeraldMike** [comment]
Interesting note when i tried to run the install command with specifing the version it didn't work and said it installed 0.1.0.

**Comment by xoofx** [comment]
Which `TargetFramework` do you have in your project? Only `net6.0`?
`dotnet-releaser` is using nothing more than `dotnet msbuild` here, so is your project build-able from `dotnet build`?

Potential related issue [Add support for COMReference items on .NET Core](https://github.com/dotnet/msbuild/issues/3986)

**Comment by EmeraldMike** [comment]
```
C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(2929,5): error : MSB4803: The task "ResolveComReference" is not supported on the .NET Core version of MSBuild. Please use the .NET Framework version of MSBuild. See https://aka.ms/msbuild/MSB4803 for further details. [C:\Users\Emera\source\repos\catoscript\cato\cato.csproj]    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.62
```
i get this when i run dotnet build

**Comment by xoofx** [comment]
Is it your project with [these lines](https://github.com/catoscript/cato/blob/ded0646185c267744173728efd4afc2bba8c18a0/cato.csproj#L12-L19) ?

Because it seems that ComReference are not supported while you are using them. 🤔

**Comment by EmeraldMike** [comment]
Yes that is my project that i am trying to cross build.
Should i remove these lines or anything?

**Comment by xoofx** [comment]
Per the MSBuild issue above, this is not supported. If you can't build a project with `dotnet build` you won't be able to build it with `dotnet-releaser` for sure.

**Comment by EmeraldMike** [comment]
Ah so removing them did allow the project to successfully build using dotnet build. Thanks!
